name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Check if build for production is passing

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Yarn
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
