name: Fixer

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Style code fixer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Yarn
        run: |
          yarn set version berry
          yarn install --frozen-lockfile

      - name: ESLint code fixer
        run: yarn eslint --fix

      - name: Style code fixer
        run: yarn prettier

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Style code
