name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Yarn
        run: yarn install --immutable-cache

      - name: Test code unit (Vitest)
        run: yarn test:unit
