name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Yarn
        run: |
          yarn set version berry
          yarn install --frozen-lockfile

      - name: Test code unit (Vitest)
        run: yarn test:unit

